---

- name: EAPI VLAN Change
  hosts: localhost
   
  tasks:
    - name: VLAN check & change
      w5_ex3_conf_module: vlan_id=909 vlan_name=GreenLantern
               eapi_username={{ eapi_username}} 
               eapi_password={{ eapi_password }} 
               eapi_hostname={{ eapi_hostname }} 
               eapi_port={{ eapi_port }}
